### ISSUE TITLE
Unimplemented type: 3

### ISSUE THREAD

**Issue by drnextgis** [mapbox/pbf#104]
I'm getting the following error while trying to add mvt layer on OpenLayers webmap:

```
Uncaught Error: Unimplemented type: 3
```

The error comes from here: https://github.com/mapbox/pbf/blob/e26454842595c3eae1f5f8281bba508fbd85b718/index.js#L200

Is it a bug or probably something wrong with tiles?

**Comment by kjvalencik** [comment]
Are you able to share a copy of the data trying to be decoded?

**Comment by drnextgis** [comment]
Yep, sure: [tile.zip](https://github.com/mapbox/pbf/files/3310115/tile.zip)

**Comment by kjvalencik** [comment]
This doesn't seem valid for the [`vector_tile.proto`](https://github.com/mapbox/pbf/blob/master/bench/vector_tile.proto).

**Comment by drnextgis** [comment]
The reason of issue is compressed tile. If pass uncompressed one then everything works.
