### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by joto** [mapbox/pbf#17]
Naming this library "PBF" is a bit confusing in the Geo-Context, because thats what OSMers call its Protobuf-based OSM data format. The German language weekly OSM report already erroneously reported this as a new library to read OSM files.

**Comment by mourner** [comment]
I think this is not a problem of the library, but rather a problem of unfortunate naming of the OSM Protobuf-based format — "pbf" is a common abbreviation for protocol buffers, so it can't be used to represent a format specific to OSM.
