### ISSUE TITLE
proto -> pbf code generation tool

### ISSUE THREAD

**Issue by mourner** [mapbox/pbf#22]
pbf is now super-fast and robust, so now we can easily make a tool for generating pbf encoding/decoding code from a proto file, which will make the library easier to use and more on par with official bindings and tools like [protocol-buffers](https://github.com/mafintosh/protocol-buffers). The tool would be an alternative way to use the library and required through a separate file.

The generated code would look [like this](https://gist.github.com/mourner/39dbf31fa1a88be00fd8) and would be usable out of the box.

**Comment by mikemorris** [comment]
:+1:
