### ISSUE TITLE
Investigate possible SIMD speedups

### ISSUE THREAD

**Issue by danpat** [mapbox/pbf#29]
Might be worth looking at this library:

https://github.com/lemire/simdcomp

and seeing if we can apply that to varint packing (or things like `repeated uint32 geometry = 4 [ packed = true ];`).

**Comment by mourner** [comment]
I guess you meant to open this in https://github.com/mapbox/pbf.hpp, since this is a JS implementation.

SIMD is cool, although I'd personally prefer to keep pbf.hpp simple — it's fast enough for most needs already. And simdcomp has _a lot_ of code.
