### ISSUE TITLE
Decoding url instead of file?

### ISSUE THREAD

**Issue by rowanwins** [mapbox/pbf#33]
Hi there,

I'm just trying to work out how to get this module to look directly a vector tile source rather than a local file

So for example this works
````
var data = fs.readFileSync(__dirname + '/data/25.Pbf');
var tile = new VectorTile(new Protobuf(data));
````
but this does not
````
var tile = new VectorTile(new Protobuf('http://localhost:7777/countries/tiles/5/17/25.pbf'));
````
I gather it's to do with making the xhr request properly, is anyone able to provide any sample code for how to easily do this in node?

Thanks in advance,
Rowan

**Comment by mourner** [comment]
See https://github.com/mapbox/tile-reduce/blob/master/src/remote.js for an example.

**Comment by rowanwins** [comment]
Thanks @mourner , fyi am looking at making a vector tiles desktop app with electron for exploring local mbtiles files
