### ISSUE TITLE
Provide roundtripping example in the docs

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/pbf#36]
At the moment the module lacks a round-tripping example as simple as:

```js
const outPbf = new Pbf();
Line.write(kLineToWrite, outPbf);
const outBuf = outPbf.finish();
fs.writeFileSync(kLinePbfFile, outBuf);

const inBuf = fs.readFileSync(kLinePbfFile);
const inPbf = new Pbf(inBuf);
const roundtrip = Line.read(inPbf);
console.log(roundtrip);
```

for the compiled code.

The readme only shows:

```js
var obj = Test.read(new Pbf(buffer)); // read
var buffer = Test.write(obj, new Pbf()); // write
```

which misses a concrete example and also the needed `finish` call.

/cc @karenzshea @miccolis

**Comment by mourner** [comment]
Thanks, fixed the readme. I didn't include `fs.readFileSync` etc. because the library is for browsers too, and `buffer` is explained [later in the readme](https://github.com/mapbox/pbf#api).
