### ISSUE TITLE
Add generated content warning to compile

### ISSUE THREAD

**Issue by kjvalencik** [mapbox/pbf#49]
It would be beneficial for adding a comment to the top of the generated javascript warning that the code is generated. Perhaps with the version of `pbf` that was used as well.

```js
// GENERATED FILE. DO NOT MODIFY. pbf v2.0.1
```

**Comment by mourner** [comment]
I had this reported before in #31, but now it's the second time, we probably should do it.

**Comment by kjvalencik** [comment]
Sorry, I should have searched for the closed issue first. :smile: I can see your point there. Maybe don't include the phrase `DO NOT MODIFY`?

**Comment by mourner** [comment]
Yeah, maybe just this:

```
// code generated by pbf v2.0.1
```
