### ISSUE TITLE
Special handling of oneof fields

### ISSUE THREAD

**Issue by mourner** [mapbox/pbf#51]
Currently we don't treat oneof fields in any special way. Should we? I'm not sure.

There's potential ambiguity after introducing default value handling:

```
oneof test {
  int32 foo = 1;
  int32 bar = 2; 
}
```

If either `foo` or `bar` is set to `0`, we will decode the message as `{foo: 0, bar: 0}`. However there will be no way to distinguish which of the fields is set when looking at the result.

One way to address this would be to decode all fields except the set one as `undefined`, or simply not to include them in the initial object.

cc @kjvalencik

**Comment by kjvalencik** [comment]
Just ran into this issue when running some tests. The way `protobufjs` handles this is setting the `test` field to the `oneof` that is actually set.

I also think `oneof` messages should be excluded from defaults.

**Comment by mourner** [comment]
> The way protobufjs handles this is setting the test field to the oneof that is actually set.

There would still be an ambiguity problem — after decoding, you wouldn't know which of the fields you decoded, and when writing, you also wouldn't know which one to encode (if they're not easily distinguishable through JS type, e.g. both integer-type).

> Also, should oneof messages be excluded from defaults?

Yes. Or the should have a default of `undefined` regardless of type.

**Comment by kjvalencik** [comment]
I'm not sure where the ambiguity is. Here's what an example would look like:

```proto
message Message {
    oneof test {
        int32 foo = 1;
        int32 bar = 2;
    }
}
```

Decoded:

```json
{
    test: "foo",
    foo: 0
}
```

**Comment by kjvalencik** [comment]
This section: https://github.com/mapbox/pbf/blob/70862a330c70b1f7f946e1407cbee0b936ecec39/compile.js#L50-L53

Could change to something like:

```js
            code += '    ' + (i ? 'else if' : 'if') +
                ' (tag === ' + field.tag + ') { ';

            if (field.oneof) {
                code += 'obj.' + field.oneof + ' = ' + JSON.stringify(field.name) + '; ';
            }

            code += 'obj.' + field.name +
                (field.repeated && !isPacked(field) ?
                    '.push(' + readCode + ')' : ' = ' + readCode) + '; }\n';
```

To then generate code that looks like:

```js
Envelope._readField = function (tag, obj, pbf) {
    if (tag === 1) { obj.test = "name"; obj.name = pbf.readString(); }
    else if (tag === 2) { obj.test = "group"; obj.group = pbf.readString(); }
};
```

**Comment by mourner** [comment]
Oh, I see now. Yeah, I think that would make sense.
