### ISSUE TITLE
Negatives numbers do not work with `int32` type

### ISSUE THREAD

**Issue by kjvalencik** [mapbox/pbf#55]
Somewhat related to https://github.com/mapbox/pbf/issues/44 since negative numbers are encoded as 64-bit numbers regardless of length.

**Comment by kjvalencik** [comment]
Wanted to follow up that I have a fix for this. Cleaning it up a bit and adding tests. Should have a PR sometime tomorrow.

**Comment by mourner** [comment]
Was fixed by https://github.com/mapbox/pbf/pull/60
