### ISSUE TITLE
Referencing imported messages does not work by namespace

### ISSUE THREAD

**Issue by kjvalencik** [mapbox/pbf#58]
The issue is that [protocol-buffers-schema](https://github.com/mafintosh/protocol-buffers-schema) does not properly handle `package` information when importing. Regardless of the `package`, messages are always flattened.

This means `.proto` files are not exchangeable between javascript and other languages. Example:

```proto
syntax = "proto3";
package Foo.Enums;

enum E {
	A = 0;
	B = 1;
}
```

```proto
syntax = "proto3";
package Foo.Bar;

message Envelope {
	.Foo.Enums.E enum = 1;
}
```

This can be worked around by updating the `getType` method to skip namespaces when they aren't found. https://github.com/mapbox/pbf/blob/e0b84b8835c053bb6391d9ad050a365ee741acef/compile.js#L93-L96

```js
function getType(ctx, field) {
    var path = field.type.split('.');
    return path.reduce(function(ctx, name) { return ctx && ctx[name]; }, ctx);
}

/* Becomes */

function getType(ctx, field) {
    var path = field.type.split('.');
    return path.reduce(function(ctx, name) { return ctx[name] || ctx; }, ctx);
}
```

The downside of this work around is that you could end up grabbing the *wrong* message. However, this could currently happen and right now `.proto` files are not interchangeable, so I think this would be a decent stop gap while waiting for an upstream fix.

Thoughts?

**Comment by mourner** [comment]
Hmm, skipping namespaces feels somehow dangerous — could lead to subtle bugs for people... How hard would it be to fix upstream? Could you file an issue there? Also, is it possible to make a better fix by using the `package` field from the schema?

The current situation isn't great too — perhaps we should also throw an error if the compiler can't resolve a message name.

**Comment by kjvalencik** [comment]
I haven't had a chance to dig into the `protocol-buffers-schema` code yet to determine level of effort. This isn't high priority for me because I can work around the issue by injecting a clean-up phase that removes namespaces before compiling.

**Comment by mourner** [comment]
@kjvalencik can you file an issue with a test case upstream?

**Comment by mourner** [comment]
Closing here in favor of https://github.com/mafintosh/protocol-buffers-schema/issues/30
