### ISSUE TITLE
Is Uint8Array's buffer over allocated？

### ISSUE THREAD

**Issue by HQidea** [mapbox/pbf#76]
Example: 
```js
// omitted...
var uint8 = pbf.finish();
console.log('uint8.length:', uint8.length);
console.log('uint8.buffer.length:', uint8.buffer.byteLength);
```
and the result is:
```
uint8.length: 79
uint8.buffer.length: 128
```

The length of uint8 doesn't match the uint8.buffer's. This will result in extra bytes (0) in Node's `Buffer` if we use `Buffer.from(uint8.buffer)`.

**Comment by mourner** [comment]
That's why you would use `Buffer.from(uint8)` instead. The return value is a Buffer slice, not a new copied buffer, for performance reasons. This is working as designed.
