### ISSUE TITLE
Parsing a packed field as unpacked causes an exception

### ISSUE THREAD

**Issue by kjvalencik** [mapbox/pbf#87]
> Protocol buffer parsers must be able to parse repeated fields that were compiled as packed as if they were not packed, and vice versa. This permits adding [packed=true] to existing fields in a forward- and backward-compatible way.

https://developers.google.com/protocol-buffers/docs/encoding#packed

I.e., the packed flag should only impact encoding and not decoding. This works expected when decoding an unpacked data on a packed field because the type field is validated before reading a packed field.

https://github.com/mapbox/pbf/blob/258c8c15c568efacd975d48c667db3261c0895ce/index.js#L397-L400

However, it does not work when reading a packed field as unpacked.

```
Unimplemented type: 4
```

This could easily be fixed by using the `readPacked*` variant on both packed and unpacked fields. However, this could have performance implications due to the extra function call and while loop.

@mourner Would you like me to put together a benchmark to evaluate the performance implications?

**Comment by mourner** [comment]
@kjvalencik sure. I hope it won't be significant.

**Comment by kjvalencik** [comment]
Reading 1000 `int32`. Yuk.

```
read with original x 40,728 ops/sec ±5.36% (80 runs sampled)
read with fixed x 21,898 ops/sec ±3.82% (83 runs sampled)
```

**Comment by kjvalencik** [comment]
Possible fix. Doesn't appear to materially impact performance, but probably needs more rigorous testing.

https://github.com/kjvalencik/pbf/tree/read-packed-unpacked

**Comment by mourner** [comment]
@kjvalencik the change looks good to me!
